name:       haskell-to-c
version:    0.0.1
synopsis:   Example of producing a C library from Haskell code
github:     jwiegley/haskell-to-c
author:     John Wiegley
maintainer: johnw@newartisans.com
category:   System
license:    MIT

dependencies:
  - base     >= 4.9   && < 5
  - vector
  - bindings-DSL

library:
  exposed-modules:
    - Library
    - MainIntf
  include-dirs:
    - .

executables:
  c-driver:
    main: main.c
    other-modules: Stub
    ghc-options: -no-hs-main
    dependencies:
      - haskell-to-c

  cpp-driver:
    main: main.cpp
    other-modules: Stub
    ghc-options: -no-hs-main
    extra-libraries:
      - c++
    dependencies:
      - haskell-to-c
